name: BuildPublish

on:
    release:
        types: [created]

jobs:
    publish:
        if: github.event_name == 'release' && github.event.action == 'created'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Install poetry
              uses: Gr1N/setup-poetry@v7
            - name: Configure poetry
              run: poetry config virtualenvs.in-project true
            - name: Build and publish
              env:
                  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
              run: poetry publish --build
